parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\Domain\Discount\PercentDiscount: ~

  App\Domain\FinalPriceCalculator:
    arguments:
      $strategies:
        - '@App\Domain\Discount\PercentDiscount'
