parameters:
  app.discount_percent: '%env(float:DISCOUNT_PERCENT)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\Domain\Discount\:
    resource: '../src/Domain/Discount/*'
    tags: ['app.discount_strategy']

  App\Domain\FinalPriceCalculator:
    arguments:
      $strategies: !tagged_iterator app.discount_strategy
      $fallbackDiscount: '%app.discount_percent%'
