services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [appnet]

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:secret@db:5432/app?serverVersion=15&charset=utf8"
    volumes:
      - ./backend:/var/www
    depends_on: [db]
    networks: [appnet]

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "3000:80"
    depends_on: [api]
    networks: [appnet]

networks:
  appnet: {}

volumes:
  db_data: {}
